[project]
name = "autoripper"
version = "0.1.0"
description = "Automatically rip and transcode disks for a Jellyfin server"
license-files = [
    "LICENSE"
]
readme = "README.md"
authors = [
    { name = "Seth Raymond", email = "seth.c.raymond@gmail.com" }
]
dependencies = [
    "grpcio (>=1.83.0,<2.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
]
requires-python = ">=3.10"

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "setuptools",
    "grpcio-tools (>=1.83.0,<2.0.0)",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = false
script = "proto_gen.py"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
